sudo: false
dist: trusty
language: java
jdk:
  - openjdk8
  - openjdk11
before_install:
  - rm ~/.m2/settings.xml || true
  - ulimit -c unlimited -S
  - mvn -N io.takari:maven:wrapper
after_success:
  - bash .travis_after_success.sh
cache:
  directories:
    - "$HOME/.m2"
env:
  global:
    - secure: "vCjKpscHhzXAxTKnPeMPOTn3LY6XSskzmGOHi9jNzncAXLs8rBv2Q+fE3zAiX0x+NQ030AeimTfCcgWCIBQuh7CbpanYJG4meaBkY8oA8qdcwYSCOSC0bMZM8GLFEhemaqFhzHLofm70XaC4KFkXyAMiz3z5wowOnah1irrCnlU="
    - secure: "uDBvetN5ZEYmOS3qn9GTOk4XGz2IOvQb7+mBtEprJFpI7hwwz6mjBs2MMeqINKC8Svw4s1CfT426bXaeLImPOIJQhvRx8NXWxrcYbnmFXgIejVvthXMpDDwgLIVxakr2SZgrvwMXu/e9rM3cma3ka5kQ0fzBIgE6OALqkvuZdaM="
