sudo: false
dist: trusty
language: java
jdk:
- openjdk8
- openjdk11
before_install:
- rm ~/.m2/settings.xml || true
- ulimit -c unlimited -S
- mvn -N io.takari:maven:wrapper
after_success:
- bash .travis_after_success.sh
cache:
  directories:
  - "$HOME/.m2"
env:
  global:
  - secure: h+RdG5sP5SH9PoGjB0K9SC+GJueLf3nz7CBkExFY1O4xQldnAjVKh335L+olS72XwqU2LFiYjULK29dKnwbblAilB3tmvEAxLpvOJiztuBfzwVokliB4N+AiF0ARu1WVunI1YaVxiEHmTmnIA9cCXOMByIDEpSDJcFyCbolknpY=
  - secure: pMwwEx5S6RJhn8GM/mB85u9yII8wn9KCSSKkkU4vjM2RXCgz/cwE8ia7dbrI/PZdILBS5+R7wV04KD/FNPnR/3JSlRLWRljuJHy3hGrvoLqlM28rAY0xkFWatSGhSSN6k31LXiETGKI9kGDJe5CCo8Vwcyfim7aYhfv93/DQbUM=
